### ISSUE TITLE
Infográfia 

### ISSUE THREAD

**Issue by 23620126** [SistemasTecTlaxiaco/infografia-23620126#2]
![35928CBE-DE6D-4F32-B419-F6B9AAC715F8](https://github.com/SistemasTecTlaxiaco/infografia-23620126/assets/143775153/dee99390-1c2c-46d6-b603-bfef3e1d2ee4)

**Comment by Felix-Angel** [comment]
Redacción y ortografía: 8%
Exposición de ideas centrales 11% (No cuenta con 10 ideas principales)
Organización de  la información: 15%
Uso de imágenes y colores: 15%
Presentación visual: 15%
Referencias: 9%
Presentación: 15%
Calificación: 17.6/20
Calificado por equipo "Mayra, Daniel, Diego, Félix"

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
